
import { Octokit } from "@octokit/rest";
import chalk from "chalk";
import fs from "fs-extra";
import path from "path";

export default (program) => {
  program
    .command("gh [action] [name]")
    .description("GitHub helpers: create-repo | create-issue | upload-files")
    .action(async (action, name) => {
      const token = process.env.GITHUB_TOKEN;
      if (!token) return console.error(chalk.red("GITHUB_TOKEN missing"));

      const octokit = new Octokit({ auth: token });

      try {
        if (action === "create-repo") {
          const resp = await octokit.rest.repos.createForAuthenticatedUser({
            name,
            private: false,
            description: "Created from mycli"
          });
          console.log(chalk.green("Repo created:"), resp.data.html_url);
        } else if (action === "create-issue") {
          const [owner, repo] = name.split("/");
          const issue = await octokit.rest.issues.create({
            owner,
            repo,
            title: "Issue from mycli",
            body: "Generated by CLI"
          });
          console.log(chalk.green("Issue created:"), issue.data.html_url);
        } else if (action === "upload-files") {
          const [owner, repo] = name.split("/");
          const filePath = path.join(process.cwd(), "index.js");
          const content = await fs.readFile(filePath, "utf8");
          await octokit.rest.repos.createOrUpdateFileContents({
            owner,
            repo,
            path: "index.js",
            message: "Add index.js via mycli",
            content: Buffer.from(content).toString("base64"),
            committer: { name: "mycli", email: "mycli@example.com" }
          });
          console.log(chalk.green("Uploaded index.js"));
        } else {
          console.log(chalk.red("Unknown action. Use create-repo | create-issue | upload-files"));
        }
      } catch (err) {
        console.error(chalk.red("GitHub action failed:"), err.message);
      }
    });
};
